// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta    `orm:"table:user, do:true"`
	Id        interface{} // 用户ID
	Mobile    interface{} // 手机号
	Nickname  interface{} // 用户昵称
	Avatar    interface{} // 用户头像地址
	Gender    interface{} // 用户性别[0:未知;1:男;2:女;]
	Password  interface{} // 用户密码
	Motto     interface{} // 用户座右铭
	Email     interface{} // 用户邮箱
	IsRobot   interface{} // 是否机器人[0:否;1:是;]
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
}
